/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Modelo.Productos;
import Modelo.ProductosDao;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mpqa1
 */
public class KARDEX extends javax.swing.JDialog {

    /**
     * Creates new form KARDEX
     */
    public KARDEX(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JScrollPane();
        TablaKardex = new javax.swing.JTable();
        Principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarKardex = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblStockValor = new javax.swing.JLabel();
        lblLotesValor = new javax.swing.JLabel();
        lblProveedorValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        TablaKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Documento", "Tipo de movimiento", "Cantidad", "Precio", "Stock inicial", "Stock final", "Lote", "COSTO TOTAL"
            }
        ));
        a1.setViewportView(TablaKardex);
        if (TablaKardex.getColumnModel().getColumnCount() > 0) {
            TablaKardex.getColumnModel().getColumn(2).setResizable(false);
        }

        Principal.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KARDEX");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("CODIGO DE PRODUCTO:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("STOCK:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("PROVEEDOR:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("LOTES:");

        btnBuscarKardex.setText("BUSCAR");
        btnBuscarKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarKardexActionPerformed(evt);
            }
        });

        txtCodigo.setColumns(10);

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel1))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblStockValor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLotesValor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lblProveedorValor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGap(402, 402, 402)
                                .addComponent(btnBuscarKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addComponent(btnBuscarKardex)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStockValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(lblLotesValor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblProveedorValor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 1245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarKardex(String codigoProducto) throws SQLException {
     DefaultTableModel m = (DefaultTableModel) TablaKardex.getModel();
    m.setRowCount(0);

     String sql =
      // INGRESOS
      "SELECT fecha_compra    AS fecha, " +
      "       numero_factura  AS documento, " +
      "       'INGRESO'       AS tipo, " +
      "       stock           AS cantidad, " +
      "       precio_compra   AS precio, " +
      "       lote            AS lote, " +
      "       (stock * precio_compra) AS costo_total " +
      "  FROM productos " +
      " WHERE codigo = ? " +

      "UNION ALL " +

      // SALIDAS
      "SELECT v.fecha                AS fecha, " +
      "       v.numero_comprobante   AS documento, " +
      "       'SALIDA'               AS tipo, " +
      "       d.cantidad             AS cantidad, " +
      "       d.precio               AS precio, " +
      "       p.lote                 AS lote, " +               // <-- p.lote, no d.lote
      "       (d.cantidad * d.precio) AS costo_total " +
      "  FROM detalle d " +
      "  JOIN ventas v    ON d.id_venta = v.id " +
      "  JOIN productos p ON d.id_pro   = p.id " +
      " WHERE p.codigo = ? " +

      "ORDER BY fecha, tipo";

    try (Connection c = new Modelo.Conexion().getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setString(1, codigoProducto);
        ps.setString(2, codigoProducto);

        try (ResultSet rs = ps.executeQuery()) {
            int saldo = 0;
            while (rs.next()) {
                Date        fecha        = rs.getDate("fecha");
                String      doc          = rs.getString("documento");
                String      tipoMov      = rs.getString("tipo");
                int         cantidad     = rs.getInt("cantidad");
                BigDecimal  precio       = rs.getBigDecimal("precio");
                int         lote         = rs.getInt("lote");
                BigDecimal  costoTotal   = rs.getBigDecimal("costo_total");

                int stockInicial = saldo;
                if ("INGRESO".equals(tipoMov)) {
                    saldo += cantidad;
                } else {
                    saldo -= cantidad;
                }
                int stockFinal = saldo;

                m.addRow(new Object[]{
                    fecha,
                    doc,
                    tipoMov,
                    cantidad,
                    precio,
                    stockInicial,
                    stockFinal,
                    lote,
                    costoTotal
                });
            }
        }
    }
}

    
    
    private void btnBuscarKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarKardexActionPerformed
         String codigo = txtCodigo.getText().trim();
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un código de producto.",
            "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        ProductosDao pdao = new ProductosDao();
        Productos prod    = pdao.buscarPorCodigo(codigo);
        if (prod == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mostrar stock total sumando todos los lotes
        int stockTotal = pdao.obtenerStockTotal(codigo);
        lblStockValor.setText(String.valueOf(stockTotal));

        lblProveedorValor.setText(prod.getProveedorPro());
        int lotes = pdao.contarLotes(codigo);
        lblLotesValor.setText(String.valueOf(lotes));

        // Cargar todos los movimientos de entrada y salida
        cargarKardex(codigo);


    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,
            "Error cargando Kardex:\n" + ex.getMessage(),
            "Kardex", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarKardexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KARDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KARDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KARDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KARDEX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KARDEX dialog = new KARDEX(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JTable TablaKardex;
    private javax.swing.JScrollPane a1;
    private javax.swing.JButton btnBuscarKardex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblLotesValor;
    private javax.swing.JLabel lblProveedorValor;
    private javax.swing.JLabel lblStockValor;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
