/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.util.Arrays;    

/**
 *
 * @author mpqa1
 */
public class Restaurar extends javax.swing.JDialog {

    /**
     * Creates new form Restaurar
     */
    public Restaurar(Sistema p, boolean modal) {
        super((java.awt.Frame) null, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnexaminarrestauracion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnrestaurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtrestaurar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));

        btnexaminarrestauracion.setBackground(new java.awt.Color(255, 255, 51));
        btnexaminarrestauracion.setFont(new java.awt.Font("Eras Bold ITC", 2, 24)); // NOI18N
        btnexaminarrestauracion.setForeground(new java.awt.Color(0, 0, 0));
        btnexaminarrestauracion.setText("examinar");
        btnexaminarrestauracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexaminarrestauracionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESTAURACION DE LA BASE DE DATOS");

        btnrestaurar.setBackground(new java.awt.Color(255, 255, 0));
        btnrestaurar.setFont(new java.awt.Font("Eras Bold ITC", 2, 24)); // NOI18N
        btnrestaurar.setForeground(new java.awt.Color(0, 0, 0));
        btnrestaurar.setText("RESTAURAR");
        btnrestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RUTA DE LA BASE:");

        jDesktopPane1.setLayer(btnexaminarrestauracion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnrestaurar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtrestaurar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(txtrestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnexaminarrestauracion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnrestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexaminarrestauracion)
                    .addComponent(txtrestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrestaurar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurarActionPerformed
String ruta = txtrestaurar.getText().trim();
        if (ruta.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Seleccione primero el archivo .sql usando 'examinar'",
                "Atención", JOptionPane.WARNING_MESSAGE);
            return;    }//GEN-LAST:event_btnrestaurarActionPerformed
File sqlFile = new File(ruta);
        if (!sqlFile.exists()) {
            JOptionPane.showMessageDialog(this,
                "El archivo no existe:\n" + ruta,
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Comando para restaurar: mysql --user=root --host=localhost proyecto
        List<String> cmd = Arrays.asList(
            "mysql",
            "--user=root",
            "--host=localhost",
            "proyecto"
        );
        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.redirectInput(sqlFile);
        pb.redirectErrorStream(true);

        try {
            Process p = pb.start();
            int exitCode = p.waitFor();
            if (exitCode == 0) {
                JOptionPane.showMessageDialog(this,
                    "Base de datos restaurada con éxito desde:\n" + ruta,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String error = new String(p.getInputStream().readAllBytes());
                JOptionPane.showMessageDialog(this,
                    "Error al restaurar la base de datos:\n" + error,
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException | InterruptedException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Excepción: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnexaminarrestauracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexaminarrestauracionActionPerformed
JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione el archivo .sql para restaurar");
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("SQL Files", "sql"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            txtrestaurar.setText(f.getAbsolutePath());
        }    }//GEN-LAST:event_btnexaminarrestauracionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexaminarrestauracion;
    private javax.swing.JButton btnrestaurar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtrestaurar;
    // End of variables declaration//GEN-END:variables
}
